In [13]:
import numpy as np
a=np.array([66,44,83,19,60,75])
#Adding all the elements of an array
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.prod(a))
print(np.size(a))
print(np.mean(a))
#cummulative summ-adding upto a num
print(np.cumsum(a))
#cummulative product-multiplying upto a num
print(np.cumprod(a))


347
19
83
20608236000
6
57.833333333333336
[ 66 110 193 212 272 347]
[         66        2904      241032     4579608   274776480 20608236000]


In [28]:
price=np.array([100,200,300,400,500])
quantity=np.array([1,2,3,4,5])
# print(price,quantity)
c=np.cumprod([price,quantity],axis=0)
print(c)
print()
print(c[1].sum())

[[ 100  200  300  400  500]
 [ 100  400  900 1600 2500]]

5500
