In [1]:
#in case of list they are automatically concatinated using + operator
new_list1=[10,29,39]
new_list2=[78,45,10]
print(new_list1+new_list2)

#But in array + operator adds the given arrays 
#soo............................................

[10, 29, 39, 78, 45, 10]


In [13]:
#Concatination in arrayss
import numpy as np
arr1=np.array([[10,29],[39,60]])
arr2=np.array([[78,45],[10,50]])
print(np.concatenate([arr1,arr2]))

[[10 29]
 [39 60]
 [78 45]
 [10 50]]


In [16]:
#printing the horizontal and vertical axis(axis=0 and axis=1)
print(np.concatenate([arr1,arr2],axis=0))#horizontal concatenation
print(np.concatenate([arr1,arr2],axis=1))#Vertical concatenation

[[10 29]
 [39 60]
 [78 45]
 [10 50]]
[[10 29 78 45]
 [39 60 10 50]]


In [17]:
#Alternative of horizontal concatenation
print(np.hstack([arr1,arr2]))

[[10 29 78 45]
 [39 60 10 50]]


In [18]:
#alternative of vertical concatenation
print(np.vstack([arr1,arr2]))

[[10 29]
 [39 60]
 [78 45]
 [10 50]]


In [29]:
#spliting arrays
a=np.array([10, 29, 39, 78, 45, 10])
#storing value in split-val
split_val=np.array_split(a,3)
print(split_val)
#among three elements of array prints index 1 element 
# i.e second element

print(split_val[1])

[array([10, 29]), array([39, 78]), array([45, 10])]
[39 78]
