In [10]:
import numpy as np
arr1=np.array([[30,40],[50,90]])
arr2=np.array([[60,70],[80,10]])
print(arr1+arr2)
print(np.add(arr1,arr2))#prints using the numpy function

[[ 90 110]
 [130 100]]
[[ 90 110]
 [130 100]]


In [6]:
arr1=np.array([[30,40],[50,90]])
arr2=np.array([[60,70],[80,10]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))#prints using the numpy function

[[-30 -30]
 [-30  80]]
[[-30 -30]
 [-30  80]]


In [7]:
arr1=np.array([[30,40],[50,90]])
arr2=np.array([[60,70],[80,10]])
print(arr1*arr2)
print(np.divide(arr1,arr2))#prints using the numpy function

[[1800 2800]
 [4000  900]]
[[0.5        0.57142857]
 [0.625      9.        ]]


In [15]:
arr1=np.array([[30,40],[50,90]])
arr2=np.array([[60,70],[80,10]])
print(arr1/arr2)
print(np.multiply(arr1,arr2))#prints using the numpy function

[[0.5        0.57142857]
 [0.625      9.        ]]
[[1800 2800]
 [4000  900]]


In [17]:
arr1=np.array([30,40,50,90])
arr2=np.array([3])
print(np.power(arr1,arr2))

[ 27000  64000 125000 729000]


In [21]:
arr1=np.array([ 16,9,4,1])
print(np.sqrt(arr1))

[4. 3. 2. 1.]
